# Generated by Django 4.2 on 2023-05-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_users_alter_articlestate_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='quoting',
            field=models.FloatField(verbose_name='Степень цитирования'),
        ),
    ]
