# Generated by Django 4.2 on 2023-05-04 09:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0003_alter_article_quoting'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_ready_to_votings',
            field=models.BooleanField(default=False, verbose_name='Готова к голосованию'),
        ),
        migrations.AlterField(
            model_name='article',
            name='users',
            field=models.ManyToManyField(related_name='articles', related_query_name='article', to=settings.AUTH_USER_MODEL, verbose_name='Проверяющие'),
        ),
    ]
