# Generated by Django 4.2 on 2023-05-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_is_ready_to_votings_alter_article_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_repulished',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата внесения правок'),
        ),
    ]
