# Generated by Django 4.2 on 2023-05-13 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_date_repulished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_repulished',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата внесения правок'),
        ),
    ]
