# Generated by Django 4.2 on 2023-05-13 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_date_repulished'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_repulished']},
        ),
    ]
