# Generated by Django 4.2 on 2023-05-15 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_article_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='quoting',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Степень цитирования'),
        ),
        migrations.AlterField(
            model_name='article',
            name='unique',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Оригинальность'),
        ),
    ]
