# Generated by Django 4.2 on 2023-05-18 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_created'], 'permissions': (('добавление_статьей', 'Добавление статьей'), ('изменение_статьей', 'Изменение статей'), ('удаление_статьей', 'Удаление статей'))},
        ),
    ]
