# Generated by Django 4.2 on 2023-05-25 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_alter_article_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_ready_to_votings',
        ),
    ]
