# Generated by Django 4.2 on 2023-06-01 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_remove_article_is_ready_to_votings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_created'], 'permissions': (('добавление_статей', 'Добавление статей'), ('изменение_статей', 'Изменение статей'), ('удаление_статей', 'Удаление статей'))},
        ),
    ]
