# Generated by Django 4.2 on 2023-05-14 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['-date_created']},
        ),
    ]
