# Generated by Django 4.2 on 2023-05-18 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_created'], 'permissions': (('добавление_пользователей', 'Добавление пользователей'), ('изменение_пользователей', 'Изменение пользователей'), ('удаление_пользователей', 'Удаление пользователей'))},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['-date_created'], 'permissions': (('добавление_должностей', 'Добавление должностей'), ('изменение_должностей', 'Изменение должностей'), ('удаление_должностей', 'Удаление должностей'))},
        ),
    ]
