# Generated by Django 4.2 on 2023-04-24 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0002_article_users_alter_articlestate_article_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(verbose_name='Дата начала')),
                ('date_end', models.DateTimeField(verbose_name='Дата завершения')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votings', related_query_name='voting', to='articles.article', verbose_name='Статья')),
            ],
        ),
        migrations.CreateModel(
            name='VotingUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed', models.BooleanField(default=False, verbose_name='Проголовал за')),
                ('date_voted', models.DateTimeField(verbose_name='Дата голоса')),
                ('date_changed', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votings.voting', verbose_name='Голосование')),
            ],
        ),
        migrations.AddField(
            model_name='voting',
            name='users',
            field=models.ManyToManyField(related_name='votings', related_query_name='voting', through='votings.VotingUsers', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
