# Generated by Django 4.2 on 2023-05-12 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voting',
            options={'ordering': ['-date_start']},
        ),
    ]
