# Generated by Django 4.2 on 2023-05-18 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_grouppermission_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergroup',
            options={'ordering': ['-id'], 'permissions': (('добавление_групп', 'Добавление групп'), ('изменение_групп', 'Изменение групп'), ('удаление_групп', 'Удаление групп'))},
        ),
    ]
