# Generated by Django 4.2 on 2023-05-18 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0011_alter_author_first_name_alter_author_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['-date_created'], 'permissions': (('добавление_авторов', 'Добавление авторов'), ('изменение_авторов', 'Изменение авторов'), ('удаление_авторов', 'Удаление авторов'))},
        ),
    ]
