# Generated by Django 4.2 on 2023-05-14 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['-date_created']},
        ),
    ]
