# Generated by Django 4.2 on 2023-05-18 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0002_alter_state_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['-date_created'], 'permissions': (('добавление_статусов', 'Добавление статусов'), ('изменение_статусов', 'Изменение статусов'), ('удаление_статусов', 'Удаление статусов'))},
        ),
    ]
