# Generated by Django 4.2 on 2023-05-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='voting',
        ),
        migrations.AddField(
            model_name='notification',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='Просмотрено'),
        ),
    ]
