# Generated by Django 4.2 on 2023-05-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_content_notification_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.TextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='subject',
            field=models.CharField(choices=[('ARTICLE_REPUBLISHED', 'Внесены правки в статью'), ('REVIEWER', 'Вы назначены рецензентом'), ('VOTING', 'Началось голосование')], null=True, verbose_name='Тема'),
        ),
    ]
