# Generated by Django 4.2 on 2023-05-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='subject',
            field=models.CharField(choices=[('Внесены правки в статью', 'Внесены правки в статью'), ('Вы назначены рецензентом', 'Вы назначены рецензентом'), ('Началось голосование', 'Началось голосование')], null=True, verbose_name='Тема'),
        ),
    ]
