# Generated by Django 4.2 on 2023-05-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['checked', '-date_created']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='subject',
            field=models.CharField(choices=[('Внесены правки в статью', 'Внесены правки в статью'), ('Вы назначены рецензентом', 'Вы назначены рецензентом'), ('Назначено голосование', 'Назначено голосование')], null=True, verbose_name='Тема'),
        ),
    ]
